# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM install
      run: npm install
    - name: NPM run build
      run: npm run build --if-present
    - name: Unit tests
      run: npm run test:unit
    - name: Integration Tests
      if: ${{ github.event_name == 'pull_request' }}
      env:
        TEST_MATRIX_USER: ${{ secrets.TEST_MATRIX_USER }}
        TEST_MATRIX_PASSWORD: ${{ secrets.TEST_MATRIX_PASSWORD }}
        TEST_MATRIX_ROOM: ${{ secrets.TEST_MATRIX_ROOM }}
        TEST_MATRIX_URL: ${{ secrets.TEST_MATRIX_URL }}
        TEST_ROOM_ID: ${{ secrets.TEST_ROOM_ID }}
      run: npm run test:integration
